/**
 * Tactical
 * Opposed Roll Resolver
 *
 * Compares the Successes generated by two Tactical rolls.
 */

/**
 * Resolve an opposed Tactical roll.
 *
 * @param {object} options
 * @param {number} options.activeSuccesses
 * Successes generated by the acting character.
 *
 * @param {number} options.opposedSuccesses
 * Successes generated by the opposing character.
 *
 * @param {boolean} options.tiesFavorActive
 * Determines who wins a tie.
 *
 * @returns {object}
 */
export function resolveTacticalOpposedRoll({
  activeSuccesses = 0,
  opposedSuccesses = 0,
  tiesFavorActive = false
} = {}) {

  const active = Math.max(
    0,
    Number(activeSuccesses) || 0
  );

  const opposed = Math.max(
    0,
    Number(opposedSuccesses) || 0
  );

  const margin =
    active - opposed;

  let winner = "opposed";

  if (active > opposed) {
    winner = "active";
  }
  else if (
    active === opposed &&
    tiesFavorActive
  ) {
    winner = "active";
  }

  const activeWins =
    winner === "active";

  return {
    activeSuccesses: active,
    opposedSuccesses: opposed,

    tie:
      active === opposed,

    tiesFavorActive,

    margin,

    winner,

    activeWins,
    opposedWins: !activeWins
  };
}
